# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import buf.validate.validate_pb2 as validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0evalidate.proto\"\xb5\x01\n\x0fRegisterRequest\x12\x18\n\x08group_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01\x12\x19\n\x05\x65mail\x18\x02 \x01(\tB\n\xbaH\x07r\x02`\x01\xc8\x01\x01\x12*\n\x08password\x18\x03 \x01(\tB\x18\xbaH\x15r\x10\x32\x0e^[a-zA-Z0-9]*$\xc8\x01\x01\x12 \n\nfirst_name\x18\x04 \x01(\tB\x0c\xbaH\tr\x04\x10\x01\x18\x64\xc8\x01\x01\x12\x1f\n\tlast_name\x18\x05 \x01(\tB\x0c\xbaH\tr\x04\x10\x01\x18\x64\xc8\x01\x01\"\xba\x01\n\x04User\x12\x10\n\x08group_id\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x12\n\nfirst_name\x18\x06 \x01(\t\x12\x11\n\tlast_name\x18\x07 \x01(\t\"]\n\x0cLoginRequest\x12\x18\n\x08group_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01\x12\x19\n\x05\x65mail\x18\x02 \x01(\tB\n\xbaH\x07r\x02`\x01\xc8\x01\x01\x12\x18\n\x08password\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01\"\x1a\n\tUserToken\x12\r\n\x05token\x18\x01 \x01(\t\"\x0c\n\nGetRequest\"W\n\rUpdateRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\"(\n\nErrorField\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t2\xc2\x01\n\x0bUserService\x12/\n\x08Register\x12\x15.user.RegisterRequest\x1a\n.user.User\"\x00\x12.\n\x05Login\x12\x12.user.LoginRequest\x1a\x0f.user.UserToken\"\x00\x12%\n\x03Get\x12\x10.user.GetRequest\x1a\n.user.User\"\x00\x12+\n\x06Update\x12\x13.user.UpdateRequest\x1a\n.user.User\"\x00\x42:Z8github.com/opensourcemicroservice/userservice/proto;userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/opensourcemicroservice/userservice/proto;user'
  _globals['_REGISTERREQUEST'].fields_by_name['group_id']._loaded_options = None
  _globals['_REGISTERREQUEST'].fields_by_name['group_id']._serialized_options = b'\272H\003\310\001\001'
  _globals['_REGISTERREQUEST'].fields_by_name['email']._loaded_options = None
  _globals['_REGISTERREQUEST'].fields_by_name['email']._serialized_options = b'\272H\007r\002`\001\310\001\001'
  _globals['_REGISTERREQUEST'].fields_by_name['password']._loaded_options = None
  _globals['_REGISTERREQUEST'].fields_by_name['password']._serialized_options = b'\272H\025r\0202\016^[a-zA-Z0-9]*$\310\001\001'
  _globals['_REGISTERREQUEST'].fields_by_name['first_name']._loaded_options = None
  _globals['_REGISTERREQUEST'].fields_by_name['first_name']._serialized_options = b'\272H\tr\004\020\001\030d\310\001\001'
  _globals['_REGISTERREQUEST'].fields_by_name['last_name']._loaded_options = None
  _globals['_REGISTERREQUEST'].fields_by_name['last_name']._serialized_options = b'\272H\tr\004\020\001\030d\310\001\001'
  _globals['_LOGINREQUEST'].fields_by_name['group_id']._loaded_options = None
  _globals['_LOGINREQUEST'].fields_by_name['group_id']._serialized_options = b'\272H\003\310\001\001'
  _globals['_LOGINREQUEST'].fields_by_name['email']._loaded_options = None
  _globals['_LOGINREQUEST'].fields_by_name['email']._serialized_options = b'\272H\007r\002`\001\310\001\001'
  _globals['_LOGINREQUEST'].fields_by_name['password']._loaded_options = None
  _globals['_LOGINREQUEST'].fields_by_name['password']._serialized_options = b'\272H\003\310\001\001'
  _globals['_REGISTERREQUEST']._serialized_start=70
  _globals['_REGISTERREQUEST']._serialized_end=251
  _globals['_USER']._serialized_start=254
  _globals['_USER']._serialized_end=440
  _globals['_LOGINREQUEST']._serialized_start=442
  _globals['_LOGINREQUEST']._serialized_end=535
  _globals['_USERTOKEN']._serialized_start=537
  _globals['_USERTOKEN']._serialized_end=563
  _globals['_GETREQUEST']._serialized_start=565
  _globals['_GETREQUEST']._serialized_end=577
  _globals['_UPDATEREQUEST']._serialized_start=579
  _globals['_UPDATEREQUEST']._serialized_end=666
  _globals['_ERRORFIELD']._serialized_start=668
  _globals['_ERRORFIELD']._serialized_end=708
  _globals['_USERSERVICE']._serialized_start=711
  _globals['_USERSERVICE']._serialized_end=905
# @@protoc_insertion_point(module_scope)
